build:
  environment:
    node:
      version: v16
    php:
      version: 8
      ini:
        xdebug.mode: coverage
    hosts:
      testcraft.test: '127.0.0.1'
    variables:
      DB_DSN: 'mysql:host=127.0.0.1;port=3306;dbname=testcraft'
      DB_USER: 'root'
      DB_PASSWORD: ''
      DB_SCHEMA: ''
      DB_TABLE_PREFIX: ''
      SECURITY_KEY: 'abcde12345'
      DEFAULT_SITE_URL: 'http://testcraft.test/'
  cache:
    directories:
      - node_modules/
      - vendor/
      - ~/.composer/cache/
  nodes:
    analysis:
      before:
        - mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE testcraft'
      project_setup:
        override:
          - true
      services:
        mysql: 5.7
      tests:
        override:
          - php-scrutinizer-run
          - js-scrutinizer-run
          - command: 'php vendor/bin/codecept run unit --coverage-xml'
            coverage:
              file: tests/_output/coverage.xml
              format: clover
checks:
  php: true
  javascript: true
coding_style:
  php: { }
filter:
  excluded_paths:
    - '*/dist/*'
    - '*/lib/*'
