build:
  environment:
    node:
      version: v8.11.4
    php:
      version: 7.3
    mysql:
      version: 5.7
    variables:
      DB_DSN: 'mysql:host=localhost;port=3306;dbname=testcraft'
      DB_USER: 'root'
      DB_PASSWORD: ''
      DB_SCHEMA: ''
      DB_TABLE_PREFIX: ''
      SECURITY_KEY: 'abcde12345'
  cache:
    directories:
      - node_modules/
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - mysql -uroot -e 'CREATE DATABASE testcraft'
  nodes:
    analysis:
      project_setup:
        override:
          - true
      tests:
        override:
          -
            command: 'php vendor/bin/codecept run unit --coverage-xml'
            coverage:
              file: tests/_output/coverage.xml
              format: clover
          - php-scrutinizer-run
          -
            command: 'phpcs-run ./src'
            use_website_config: false
          - js-scrutinizer-run
          - true
checks:
  php: true
  javascript: true
coding_style:
  php: {  }
filter:
  excluded_paths:
    - '*/dist/*'
    - '*/lib/*'
